FROM condaforge/miniforge3:latest
LABEL org.opencontainers.image.authors="us@couchbits.com"
LABEL org.opencontainers.image.vendor="couchbits GmbH"

ENV PROJECT_DIR /moveapps-python-sdk
ENV ENV_PREFIX=${PROJECT_DIR}/conda

# the app
WORKDIR $PROJECT_DIR
COPY sdk.py environment.yml ./
COPY sdk/ ./sdk/
COPY resources/ ./resources/
COPY tests/ ./tests/
COPY app/ ./app/
RUN conda env create --prefix ${ENV_PREFIX}  --file environment.yml && \
    conda clean --all --yes

RUN conda run --no-capture-output --prefix ${ENV_PREFIX} python3 -m unittest