FROM mambaorg/micromamba:1.2.0-bullseye-slim
LABEL org.opencontainers.image.authors="us@couchbits.com"
LABEL org.opencontainers.image.vendor="couchbits GmbH"

COPY --chown=$MAMBA_USER:$MAMBA_USER environment.yml /tmp/env.yaml
RUN micromamba install -y -n base -f /tmp/env.yaml && \
    micromamba clean --all --yes

# the app
ENV PROJECT_DIR /moveapps-python-sdk
WORKDIR $PROJECT_DIR
COPY --chown=$MAMBA_USER:$MAMBA_USER sdk.py ./
COPY --chown=$MAMBA_USER:$MAMBA_USER sdk/ ./sdk/
COPY --chown=$MAMBA_USER:$MAMBA_USER resources/ ./resources/
COPY --chown=$MAMBA_USER:$MAMBA_USER tests/ ./tests/
COPY --chown=$MAMBA_USER:$MAMBA_USER app/ ./app/
RUN ls -al

RUN micromamba run -n base python -m unittest